require('dotenv').config();

const getGcpConfig = () => {
  const {
    GCP_PROJECT_ID,
    GCP_REGION,
    CLOUD_SQL_INSTANCE_NAME,
    CLOUD_SQL_DATABASE_NAME,
    CLOUD_SQL_USER,
    CLOUD_SQL_PASSWORD,
    REDIS_HOST,
    REDIS_PORT,
    FIRESTORE_COLLECTION,
    VERTEX_AI_ENDPOINT,
    GCS_BUCKET_NAME
  } = process.env;

  const CLOUD_SQL_CONNECTION_NAME = `${GCP_PROJECT_ID}:${GCP_REGION}:${CLOUD_SQL_INSTANCE_NAME}`;
  const DATABASE_URL = `postgresql://${CLOUD_SQL_USER}:${CLOUD_SQL_PASSWORD}@/${CLOUD_SQL_DATABASE_NAME}?host=/cloudsql/${CLOUD_SQL_CONNECTION_NAME}`;
  const REDIS_URL = `redis://${REDIS_HOST}:${REDIS_PORT}`;

  return {
    GCP_PROJECT_ID,
    GCP_REGION,
    CLOUD_SQL_INSTANCE_NAME,
    CLOUD_SQL_DATABASE_NAME,
    CLOUD_SQL_USER,
    CLOUD_SQL_PASSWORD,
    CLOUD_SQL_CONNECTION_NAME,
    REDIS_HOST,
    REDIS_PORT,
    FIRESTORE_COLLECTION,
    VERTEX_AI_ENDPOINT,
    GCS_BUCKET_NAME,
    DATABASE_URL,
    REDIS_URL
  };
};

module.exports = getGcpConfig;