runtime: nodejs20

env_variables:
  NODE_ENV: 'production'
  # Add other environment variables here, but DO NOT include sensitive information

handlers:
- url: /.*
  secure: always
  redirect_http_response_code: 301
  script: auto

# Automatic scaling configuration
automatic_scaling:
  min_instances: 1
  max_instances: 10
  min_idle_instances: 1
  max_idle_instances: automatic
  min_pending_latency: automatic
  max_pending_latency: automatic
  max_concurrent_requests: 50

# Network settings
network:
  session_affinity: true

# Resources allocation
resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

# Health check
health_check:
  enable_health_check: true
  check_interval_sec: 5
  timeout_sec: 4
  unhealthy_threshold: 2
  healthy_threshold: 2

# Includes
includes:
- secret_manager.yaml